import { SettingsInterface } from "../typings/types.js";

export const DefaultSettings: SettingsInterface[] = [
  {
    "id": "1",
    "name": "Sen's 'Person Mode' 8k Preset",
    "context_length": 8096,
    "max_tokens": 250,
    "min_tokens": 0,
    "temperature": 0.83,
    "rep_pen": 1.1,
    "rep_pen_range": 4096,
    "rep_pen_slope": 0.9,
    "frequency_penalty": 0.8,
    "presence_penalty": 0.6,
    "min_p": 0.6,
    "top_a": 0,
    "top_k": 40,
    "top_p": 0.9,
    "typical": 1,
    "tfs": 1,
    "banned_tokens": [],
    "sampler_order": [
      6,
      3,
      2,
      5,
      0,
      1,
      4
    ],
    "sampler_full_determinism": true,
    "singleline": false,
    "mirostat_eta": 0,
    "mirostat_mode": 0,
    "mirostat_tau": 0,
    "instruct_mode": "None",
    "use_beam_search": false,
    "eta_cutoff": 0,
    "epsilon_cutoff": 0,
    "dynatemp_exponent": 0,
    "dynatemp_max": 0,
    "dynatemp_min": 0,
    "length_penalty": false
  },
  {
    id: '2',
    name: 'Asper Kayra',
    rep_pen: 1.68,
    rep_pen_range: 2240,
    rep_pen_slope: 1.5,
    temperature: 1.16,
    banned_tokens: [],
    sampler_order: [5, 0, 1, 3],
    top_k: 175,
    top_p: 0.96,
    top_a: 0.0,
    min_p: 0.0,
    presence_penalty: 0.005,
    frequency_penalty: 0,
    tfs: 0.0,
    typical: 0.96,
    singleline: false,
    sampler_full_determinism: false,
    min_tokens: 1,
    context_length: 8096,
    max_tokens: 150,
    mirostat_mode: 0,
    mirostat_tau: 0.0,
    mirostat_eta: 0.0,
    instruct_mode: 'None',
    use_beam_search: false,
    eta_cutoff: 0,
    epsilon_cutoff: 0,
    dynatemp_exponent: 0,
    dynatemp_max: 0,
    dynatemp_min: 0,
    length_penalty: false,
  },
  {
    id: '3',
    name: "Blended Coffee Kayra",
    rep_pen: 1.6,
    rep_pen_range: 0,
    rep_pen_slope: 0,
    temperature: 1,
    banned_tokens: [],
    sampler_order: [6, 0, 1, 2, 3],
    top_k: 25,
    top_p: 1,
    top_a: 0,
    min_p: 0.6,
    presence_penalty: 0,
    frequency_penalty: 0.001,
    tfs: 1,
    typical: 1,
    singleline: false,
    sampler_full_determinism: true,
    min_tokens: 1,
    context_length: 8096,
    max_tokens: 150,
    mirostat_mode: 0,
    mirostat_tau: 0,
    mirostat_eta: 0,
    instruct_mode: 'None',
    use_beam_search: false,
    eta_cutoff: 0,
    epsilon_cutoff: 0,
    dynatemp_exponent: 0,
    dynatemp_max: 0,
    dynatemp_min: 0,
    length_penalty: false,
  },
  {
    id: '4',
    name: "Blook Kayra",
    rep_pen: 2,
    rep_pen_range: 0,
    rep_pen_slope: 1,
    temperature: 1,
    banned_tokens: [],
    sampler_order: [6, 2, 3, 1, 0],
    top_k: 0,
    top_p: 0.96,
    top_a: 0,
    min_p: 0.6,
    presence_penalty: 0.3,
    frequency_penalty: 0.02,
    tfs: 1,
    typical: 1,
    singleline: false,
    sampler_full_determinism: true,
    min_tokens: 1,
    context_length: 8096,
    max_tokens: 150,
    mirostat_mode: 0,
    mirostat_tau: 0,
    mirostat_eta: 0,
    instruct_mode: 'None',
    use_beam_search: false,
    eta_cutoff: 0,
    epsilon_cutoff: 0,
    dynatemp_exponent: 0,
    dynatemp_max: 0,
    dynatemp_min: 0,
    length_penalty: false,
  },
  {
    id: '5',
    name: 'Green Active Writer Kayra',
    rep_pen: 1,
    rep_pen_range: 1632,
    rep_pen_slope: 0.9,
    temperature: 1.5,
    banned_tokens: [],
    sampler_order: [6, 0, 8, 5, 3],
    top_k: 40,
    top_p: 0.9,
    top_a: 0,
    min_p: 0.6,
    presence_penalty: 0,
    frequency_penalty: 0,
    tfs: 1,
    typical: 1,
    singleline: false,
    sampler_full_determinism: true,
    min_tokens: 1,
    context_length: 8096,
    max_tokens: 150,
    mirostat_mode: 0,
    mirostat_tau: 0,
    mirostat_eta: 0,
    instruct_mode: 'None',
    use_beam_search: false,
    eta_cutoff: 0,
    epsilon_cutoff: 0,
    dynatemp_exponent: 0,
    dynatemp_max: 0,
    dynatemp_min: 0,
    length_penalty: false,
  },
  {
    id: '6',
    name: 'Keelback Clio',
    rep_pen: 1.25,
    rep_pen_range: 4096,
    rep_pen_slope: 0.9,
    temperature: 1.18,
    banned_tokens: [],
    sampler_order: [4, 5, 0, 3],
    top_k: 0,
    top_p: 1,
    top_a: 0,
    min_p: 0.6,
    presence_penalty: 0,
    frequency_penalty: 0,
    tfs: 1,
    typical: 1,
    singleline: false,
    sampler_full_determinism: true,
    min_tokens: 1,
    context_length: 8096,
    max_tokens: 40,
    mirostat_mode: 0,
    mirostat_tau: 0,
    mirostat_eta: 0,
    instruct_mode: 'None',
    use_beam_search: false,
    eta_cutoff: 0,
    epsilon_cutoff: 0,
    dynatemp_exponent: 0,
    dynatemp_max: 0,
    dynatemp_min: 0,
    length_penalty: false,
  },
  {
    id: '7',
    name: 'Long Press Clio',
    rep_pen: 1.0125,
    rep_pen_range: 2048,
    rep_pen_slope: 3.33,
    temperature: 1.155,
    banned_tokens: [],
    sampler_order: [0, 4, 1, 5, 3],
    top_k: 25,
    top_p: 1,
    top_a: 0,
    min_p: 0.6,
    presence_penalty: 0.005,
    frequency_penalty: 0.011,
    tfs: 1,
    typical: 1,
    singleline: false,
    sampler_full_determinism: true,
    min_tokens: 1,
    context_length: 8096,
    max_tokens: 40,
    mirostat_mode: 0,
    mirostat_tau: 0,
    mirostat_eta: 0,
    instruct_mode: 'None',
    use_beam_search: false,
    eta_cutoff: 0,
    epsilon_cutoff: 0,
    dynatemp_exponent: 0,
    dynatemp_max: 0,
    dynatemp_min: 0,
    length_penalty: false,
  },
  {
    id: '8',
    name: 'Pilotfish Kayra',
    rep_pen: 1.55,
    rep_pen_range: 8192,
    rep_pen_slope: 1.8,
    temperature: 1.31,
    banned_tokens: [],
    sampler_order: [6, 0, 4, 1, 2, 5, 3],
    top_k: 25,
    top_p: 0.97,
    top_a: 0,
    min_p: 0.6,
    presence_penalty: 0.00085,
    frequency_penalty: 0.00075,
    tfs: 1,
    typical: 1,
    singleline: false,
    sampler_full_determinism: true,
    min_tokens: 1,
    context_length: 8096,
    max_tokens: 150,
    mirostat_mode: 0,
    mirostat_tau: 0,
    mirostat_eta: 0,
    instruct_mode: 'None',
    use_beam_search: false,
    eta_cutoff: 0,
    epsilon_cutoff: 0,
    dynatemp_exponent: 0,
    dynatemp_max: 0,
    dynatemp_min: 0,
    length_penalty: false,
  },
  {
    id: '9',
    name: 'Pro Writer Kayra',
    rep_pen: 1.86,
    rep_pen_range: 2048,
    rep_pen_slope: 2.33,
    temperature: 1.06,
    banned_tokens: [],
    sampler_order: [3, 4, 5, 0],
    top_k: 40,
    top_p: 0.9,
    top_a: 0,
    min_p: 0.6,
    presence_penalty: 0,
    frequency_penalty: 0,
    tfs: 1,
    typical: 1,
    singleline: false,
    sampler_full_determinism: true,
    min_tokens: 1,
    context_length: 8096,
    max_tokens: 150,
    mirostat_mode: 0,
    mirostat_tau: 0,
    mirostat_eta: 0,
    instruct_mode: 'None',
    use_beam_search: false,
    eta_cutoff: 0,
    epsilon_cutoff: 0,
    dynatemp_exponent: 0,
    dynatemp_max: 0,
    dynatemp_min: 0,
    length_penalty: false,
  },
  {
    id: '10',
    name: 'Stelenes Kayra',
    rep_pen: 1,
    rep_pen_range: 1024,
    rep_pen_slope: 0.9,
    temperature: 2.5,
    banned_tokens: [],
    sampler_order: [3, 0, 5],
    top_k: 40,
    top_p: 0.9,
    top_a: 0,
    min_p: 0.6,
    presence_penalty: 0,
    frequency_penalty: 0,
    tfs: 1,
    typical: 1,
    singleline: false,
    sampler_full_determinism: true,
    min_tokens: 1,
    context_length: 8096,
    max_tokens: 150,
    mirostat_mode: 0,
    mirostat_tau: 0,
    mirostat_eta: 0,
    instruct_mode: 'None',
    use_beam_search: false,
    eta_cutoff: 0,
    epsilon_cutoff: 0,
    dynatemp_exponent: 0,
    dynatemp_max: 0,
    dynatemp_min: 0,
    length_penalty: false,
  },
  {
    id: '11',
    name: 'Talker Chat Clio',
    rep_pen: 2.25,
    rep_pen_range: 8192,
    rep_pen_slope: 0.09,
    temperature: 1.5,
    banned_tokens: [],
    sampler_order: [1, 5, 0, 2, 3, 4],
    top_k: 10,
    top_p: 0.75,
    top_a: 0,
    min_p: 0.6,
    presence_penalty: 0.005,
    frequency_penalty: 0,
    tfs: 1,
    typical: 1,
    singleline: false,
    sampler_full_determinism: true,
    min_tokens: 1,
    context_length: 8096,
    max_tokens: 150,
    mirostat_mode: 0,
    mirostat_tau: 0,
    mirostat_eta: 0,
    instruct_mode: 'None',
    use_beam_search: false,
    eta_cutoff: 0,
    epsilon_cutoff: 0,
    dynatemp_exponent: 0,
    dynatemp_max: 0,
    dynatemp_min: 0,
    length_penalty: false,
  },
  {
    id: '12',
    name: 'Tea Time Kayra',
    rep_pen: 3,
    rep_pen_range: 7680,
    rep_pen_slope: 0.09,
    temperature: 1,
    banned_tokens: [],
    sampler_order: [5, 0, 4],
    top_k: 40,
    top_p: 0.9,
    top_a: 0,
    min_p: 0.6,
    presence_penalty: 0,
    frequency_penalty: 0,
    tfs: 1,
    typical: 1,
    singleline: false,
    sampler_full_determinism: true,
    min_tokens: 1,
    context_length: 8096,
    max_tokens: 150,
    mirostat_mode: 0,
    mirostat_tau: 0,
    mirostat_eta: 0,
    instruct_mode: 'None',
    use_beam_search: false,
    eta_cutoff: 0,
    epsilon_cutoff: 0,
    dynatemp_exponent: 0,
    dynatemp_max: 0,
    dynatemp_min: 0,
    length_penalty: false,
  },
  {
    id: '13',
    name: 'Tesseract Kayra',
    rep_pen: 2,
    rep_pen_range: 4048,
    rep_pen_slope: 3.2,
    temperature: 0.895,
    banned_tokens: [],
    sampler_order: [6, 0, 5],
    top_k: 40,
    top_p: 0.9,
    top_a: 0,
    min_p: 0.6,
    presence_penalty: 0,
    frequency_penalty: 0,
    tfs: 1,
    typical: 1,
    singleline: false,
    sampler_full_determinism: true,
    min_tokens: 1,
    context_length: 8096,
    max_tokens: 150,
    mirostat_mode: 0,
    mirostat_tau: 0,
    mirostat_eta: 0,
    instruct_mode: 'None',
    use_beam_search: false,
    eta_cutoff: 0,
    epsilon_cutoff: 0,
    dynatemp_exponent: 0,
    dynatemp_max: 0,
    dynatemp_min: 0,
    length_penalty: false,
  },
  {
    id: '14',
    name: 'Vingt Un Clio',
    rep_pen: 1.21,
    rep_pen_range: 321,
    rep_pen_slope: 3.33,
    temperature: 1.21,
    banned_tokens: [],
    sampler_order: [0, 5, 3, 2, 1],
    top_k: 0,
    top_p: 0.912,
    top_a: 0,
    min_p: 0.6,
    presence_penalty: 0,
    frequency_penalty: 0.00621,
    tfs: 1,
    typical: 1,
    singleline: false,
    sampler_full_determinism: true,
    min_tokens: 1,
    context_length: 8096,
    max_tokens: 40,
    mirostat_mode: 0,
    mirostat_tau: 0,
    mirostat_eta: 0,
    instruct_mode: 'None',
    use_beam_search: false,
    eta_cutoff: 0,
    epsilon_cutoff: 0,
    dynatemp_exponent: 0,
    dynatemp_max: 0,
    dynatemp_min: 0,
    length_penalty: false,
  },
  {
    id: '15',
    name: 'Writers Daemon Kayra',
    rep_pen: 1.625,
    rep_pen_range: 2016,
    rep_pen_slope: 0.9,
    temperature: 1.5,
    banned_tokens: [],
    sampler_order: [8, 0, 5, 3, 2, 4],
    top_k: 40,
    top_p: 0.95,
    top_a: 0,
    min_p: 0.6,
    presence_penalty: 0,
    frequency_penalty: 0,
    tfs: 1,
    typical: 1,
    singleline: false,
    sampler_full_determinism: true,
    min_tokens: 1,
    context_length: 8096,
    max_tokens: 150,
    mirostat_mode: 0,
    mirostat_tau: 0,
    mirostat_eta: 0,
    instruct_mode: 'None',
    use_beam_search: false,
    eta_cutoff: 0,
    epsilon_cutoff: 0,
    dynatemp_exponent: 0,
    dynatemp_max: 0,
    dynatemp_min: 0,
    length_penalty: false,
  },
  {
    id: '16',
    name: 'Ace of Spades',
    rep_pen: 1.1,
    rep_pen_range: 4096,
    rep_pen_slope: 0.9,
    temperature: 0.83,
    banned_tokens: [],
    sampler_order: [6, 3, 2, 5, 0, 1, 4],
    top_k: 0,
    top_p: 0.95,
    top_a: 0,
    min_p: 0.6,
    presence_penalty: 0.6,
    frequency_penalty: 0.8,
    tfs: 1,
    typical: 1,
    singleline: false,
    sampler_full_determinism: true,
    min_tokens: 0,
    context_length: 8096,
    max_tokens: 250,
    mirostat_mode: 0,
    mirostat_tau: 0,
    mirostat_eta: 0,
    instruct_mode: 'None',
    use_beam_search: false,
    eta_cutoff: 0,
    epsilon_cutoff: 0,
    dynatemp_exponent: 0,
    dynatemp_max: 0,
    dynatemp_min: 0,
    length_penalty: false,
  },
  {
    id: '17',
    name: 'Basic Coherence',
    rep_pen: 1.1,
    rep_pen_range: 4096,
    rep_pen_slope: 0.9,
    temperature: 0.83,
    banned_tokens: [],
    sampler_order: [6, 3, 2, 5, 0, 1, 4],
    top_k: 0,
    top_p: 1,
    top_a: 0,
    min_p: 0.6,
    presence_penalty: 0.6,
    frequency_penalty: 0.8,
    tfs: 1,
    typical: 1,
    singleline: false,
    sampler_full_determinism: true,
    min_tokens: 0,
    context_length: 8096,
    max_tokens: 250,
    mirostat_mode: 0,
    mirostat_tau: 0,
    mirostat_eta: 0,
    instruct_mode: 'None',
    use_beam_search: false,
    eta_cutoff: 0,
    epsilon_cutoff: 0,
    dynatemp_exponent: 0,
    dynatemp_max: 0,
    dynatemp_min: 0,
    length_penalty: false,
  },
  {
    id: '18',
    name: 'Best Guess',
    rep_pen: 1.1,
    rep_pen_range: 4096,
    rep_pen_slope: 0.9,
    temperature: 0.83,
    banned_tokens: [],
    sampler_order: [6, 3, 2, 5, 0, 1, 4],
    top_k: 100,
    top_p: 0.9,
    top_a: 0,
    min_p: 0.6,
    presence_penalty: 0.6,
    frequency_penalty: 0.8,
    tfs: 1,
    typical: 1,
    singleline: false,
    sampler_full_determinism: true,
    min_tokens: 0,
    context_length: 8096,
    max_tokens: 250,
    mirostat_mode: 0,
    mirostat_tau: 0,
    mirostat_eta: 0,
    instruct_mode: 'None',
    use_beam_search: false,
    eta_cutoff: 0,
    epsilon_cutoff: 0,
    dynatemp_exponent: 0,
    dynatemp_max: 0,
    dynatemp_min: 0,
    length_penalty: false,
  },
  {
    id: '19',
    name: 'Coherent Creativity',
    rep_pen: 1.1,
    rep_pen_range: 4096,
    rep_pen_slope: 0.9,
    temperature: 0.83,
    banned_tokens: [],
    sampler_order: [6, 3, 2, 5, 0, 1, 4],
    top_k: 0,
    top_p: 1,
    top_a: 0,
    min_p: 0.6,
    presence_penalty: 0.6,
    frequency_penalty: 0.8,
    tfs: 1,
    typical: 1,
    singleline: false,
    sampler_full_determinism: true,
    min_tokens: 0,
    context_length: 8096,
    max_tokens: 250,
    mirostat_mode: 0,
    mirostat_tau: 0,
    mirostat_eta: 0,
    instruct_mode: 'None',
    use_beam_search: false,
    eta_cutoff: 0,
    epsilon_cutoff: 0,
    dynatemp_exponent: 0,
    dynatemp_max: 0,
    dynatemp_min: 0,
    length_penalty: false,
  },
  {
    id: '20',
    name: 'Deterministic',
    rep_pen: 1.1,
    rep_pen_range: 4096,
    rep_pen_slope: 0.9,
    temperature: 0.83,
    banned_tokens: [],
    sampler_order: [6, 3, 2, 5, 0, 1, 4],
    top_k: 1,
    top_p: 0,
    top_a: 0,
    min_p: 0.6,
    presence_penalty: 0.6,
    frequency_penalty: 0.8,
    tfs: 1,
    typical: 1,
    singleline: false,
    sampler_full_determinism: true,
    min_tokens: 0,
    context_length: 8096,
    max_tokens: 250,
    mirostat_mode: 0,
    mirostat_tau: 0,
    mirostat_eta: 0,
    instruct_mode: 'None',
    use_beam_search: false,
    eta_cutoff: 0,
    epsilon_cutoff: 0,
    dynatemp_exponent: 0,
    dynatemp_max: 0,
    dynatemp_min: 0,
    length_penalty: false,
  },
  {
    id: '21',
    name: 'Genesis',
    rep_pen: 1.1,
    rep_pen_range: 4096,
    rep_pen_slope: 0.9,
    temperature: 0.83,
    banned_tokens: [],
    sampler_order: [6, 3, 2, 5, 0, 1, 4],
    top_k: 0,
    top_p: 0.98,
    top_a: 0,
    min_p: 0.6,
    presence_penalty: 0.6,
    frequency_penalty: 0.8,
    tfs: 1,
    typical: 1,
    singleline: false,
    sampler_full_determinism: true,
    min_tokens: 0,
    context_length: 8096,
    max_tokens: 250,
    mirostat_mode: 0,
    mirostat_tau: 0,
    mirostat_eta: 0,
    instruct_mode: 'None',
    use_beam_search: false,
    eta_cutoff: 0,
    epsilon_cutoff: 0,
    dynatemp_exponent: 0,
    dynatemp_max: 0,
    dynatemp_min: 0,
    length_penalty: false,
  },
  {
    id: '22',
    name: 'Godlike',
    rep_pen: 1.1,
    rep_pen_range: 4096,
    rep_pen_slope: 0.9,
    temperature: 0.83,
    banned_tokens: [],
    sampler_order: [6, 3, 2, 5, 0, 1, 4],
    top_k: 0,
    top_p: 0.5,
    top_a: 0,
    min_p: 0.6,
    presence_penalty: 0.6,
    frequency_penalty: 0.8,
    tfs: 1,
    typical: 1,
    singleline: false,
    sampler_full_determinism: true,
    min_tokens: 0,
    context_length: 8096,
    max_tokens: 250,
    mirostat_mode: 0,
    mirostat_tau: 0,
    mirostat_eta: 0,
    instruct_mode: 'None',
    use_beam_search: false,
    eta_cutoff: 0,
    epsilon_cutoff: 0,
    dynatemp_exponent: 0,
    dynatemp_max: 0,
    dynatemp_min: 0,
    length_penalty: false,
  },
  {
    id: '23',
    name: 'Good Winds',
    rep_pen: 1.1,
    rep_pen_range: 4096,
    rep_pen_slope: 0.9,
    temperature: 0.83,
    banned_tokens: [],
    sampler_order: [6, 3, 2, 5, 0, 1, 4],
    top_k: 0,
    top_p: 1,
    top_a: 0,
    min_p: 0.6,
    presence_penalty: 0.6,
    frequency_penalty: 0.8,
    tfs: 1,
    typical: 1,
    singleline: false,
    sampler_full_determinism: true,
    min_tokens: 0,
    context_length: 8096,
    max_tokens: 250,
    mirostat_mode: 0,
    mirostat_tau: 0,
    mirostat_eta: 0,
    instruct_mode: 'None',
    use_beam_search: false,
    eta_cutoff: 0,
    epsilon_cutoff: 0,
    dynatemp_exponent: 0,
    dynatemp_max: 0,
    dynatemp_min: 0,
    length_penalty: false,
  },
  {
    id: '24',
    name: 'Liminal Drift',
    rep_pen: 1.1,
    rep_pen_range: 4096,
    rep_pen_slope: 0.9,
    temperature: 0.83,
    banned_tokens: [],
    sampler_order: [6, 3, 2, 5, 0, 1, 4],
    top_k: 0,
    top_p: 1,
    top_a: 0,
    min_p: 0.6,
    presence_penalty: 0.6,
    frequency_penalty: 0.8,
    tfs: 1,
    typical: 1,
    singleline: false,
    sampler_full_determinism: true,
    min_tokens: 0,
    context_length: 8096,
    max_tokens: 250,
    mirostat_mode: 0,
    mirostat_tau: 0,
    mirostat_eta: 0,
    instruct_mode: 'None',
    use_beam_search: false,
    eta_cutoff: 0,
    epsilon_cutoff: 0,
    dynatemp_exponent: 0,
    dynatemp_max: 0,
    dynatemp_min: 0,
    length_penalty: false,
  },
  {
    id: '25',
    name: 'Low Rider',
    rep_pen: 1.1,
    rep_pen_range: 4096,
    rep_pen_slope: 0.9,
    temperature: 0.83,
    banned_tokens: [],
    sampler_order: [6, 3, 2, 5, 0, 1, 4],
    top_k: 12,
    top_p: 1,
    top_a: 0,
    min_p: 0.6,
    presence_penalty: 0.6,
    frequency_penalty: 0.8,
    tfs: 1,
    typical: 1,
    singleline: false,
    sampler_full_determinism: true,
    min_tokens: 0,
    context_length: 8096,
    max_tokens: 250,
    mirostat_mode: 0,
    mirostat_tau: 0,
    mirostat_eta: 0,
    instruct_mode: 'None',
    use_beam_search: false,
    eta_cutoff: 0,
    epsilon_cutoff: 0,
    dynatemp_exponent: 0,
    dynatemp_max: 0,
    dynatemp_min: 0,
    length_penalty: false,
  },
  {
    id: '26',
    name: 'Luna Moth',
    rep_pen: 1.1,
    rep_pen_range: 4096,
    rep_pen_slope: 0.9,
    temperature: 0.83,
    banned_tokens: [],
    sampler_order: [6, 3, 2, 5, 0, 1, 4],
    top_k: 85,
    top_p: 0.24,
    top_a: 0,
    min_p: 0.6,
    presence_penalty: 0.6,
    frequency_penalty: 0.8,
    tfs: 1,
    typical: 1,
    singleline: false,
    sampler_full_determinism: true,
    min_tokens: 0,
    context_length: 8096,
    max_tokens: 250,
    mirostat_mode: 0,
    mirostat_tau: 0,
    mirostat_eta: 0,
    instruct_mode: 'None',
    use_beam_search: false,
    eta_cutoff: 0,
    epsilon_cutoff: 0,
    dynatemp_exponent: 0,
    dynatemp_max: 0,
    dynatemp_min: 0,
    length_penalty: false,
  },
  {
    id: '27',
    name: 'Mayday',
    rep_pen: 1.1,
    rep_pen_range: 4096,
    rep_pen_slope: 0.9,
    temperature: 0.83,
    banned_tokens: [],
    sampler_order: [6, 3, 2, 5, 0, 1, 4],
    top_k: 0,
    top_p: 0.95,
    top_a: 0,
    min_p: 0.6,
    presence_penalty: 0.6,
    frequency_penalty: 0.8,
    tfs: 1,
    typical: 1,
    singleline: false,
    sampler_full_determinism: true,
    min_tokens: 0,
    context_length: 8096,
    max_tokens: 250,
    mirostat_mode: 0,
    mirostat_tau: 0,
    mirostat_eta: 0,
    instruct_mode: 'None',
    use_beam_search: false,
    eta_cutoff: 0,
    epsilon_cutoff: 0,
    dynatemp_exponent: 0,
    dynatemp_max: 0,
    dynatemp_min: 0,
    length_penalty: false,
  },
  {
    id: '28',
    name: 'Miro Bronze',
    rep_pen: 1.1,
    rep_pen_range: 4096,
    rep_pen_slope: 0.9,
    temperature: 0.83,
    banned_tokens: [],
    sampler_order: [6, 3, 2, 5, 0, 1, 4],
    top_k: 0,
    top_p: 1,
    top_a: 0,
    min_p: 0.6,
    presence_penalty: 0.6,
    frequency_penalty: 0.8,
    tfs: 1,
    typical: 1,
    singleline: false,
    sampler_full_determinism: true,
    min_tokens: 0,
    context_length: 8096,
    max_tokens: 250,
    mirostat_mode: 0,
    mirostat_tau: 0,
    mirostat_eta: 0,
    instruct_mode: 'None',
    use_beam_search: false,
    eta_cutoff: 0,
    epsilon_cutoff: 0,
    dynatemp_exponent: 0,
    dynatemp_max: 0,
    dynatemp_min: 0,
    length_penalty: false,
  },
  {
    id: '29',
    name: 'Miro Gold',
    rep_pen: 1.1,
    rep_pen_range: 4096,
    rep_pen_slope: 0.9,
    temperature: 0.83,
    banned_tokens: [],
    sampler_order: [6, 3, 2, 5, 0, 1, 4],
    top_k: 0,
    top_p: 1,
    top_a: 0,
    min_p: 0.6,
    presence_penalty: 0.6,
    frequency_penalty: 0.8,
    tfs: 1,
    typical: 1,
    singleline: false,
    sampler_full_determinism: true,
    min_tokens: 0,
    context_length: 8096,
    max_tokens: 250,
    mirostat_mode: 0,
    mirostat_tau: 0,
    mirostat_eta: 0,
    instruct_mode: 'None',
    use_beam_search: false,
    eta_cutoff: 0,
    epsilon_cutoff: 0,
    dynatemp_exponent: 0,
    dynatemp_max: 0,
    dynatemp_min: 0,
    length_penalty: false,
  },
  {
    id: '30',
    name: 'Miro Silver',
    rep_pen: 1.1,
    rep_pen_range: 4096,
    rep_pen_slope: 0.9,
    temperature: 0.83,
    banned_tokens: [],
    sampler_order: [6, 3, 2, 5, 0, 1, 4],
    top_k: 0,
    top_p: 1,
    top_a: 0,
    min_p: 0.6,
    presence_penalty: 0.6,
    frequency_penalty: 0.8,
    tfs: 1,
    typical: 1,
    singleline: false,
    sampler_full_determinism: true,
    min_tokens: 0,
    context_length: 8096,
    max_tokens: 250,
    mirostat_mode: 0,
    mirostat_tau: 0,
    mirostat_eta: 0,
    instruct_mode: 'None',
    use_beam_search: false,
    eta_cutoff: 0,
    epsilon_cutoff: 0,
    dynatemp_exponent: 0,
    dynatemp_max: 0,
    dynatemp_min: 0,
    length_penalty: false,
  },
  {
    id: '31',
    name: 'Ouroboros',
    rep_pen: 1.1,
    rep_pen_range: 4096,
    rep_pen_slope: 0.9,
    temperature: 0.83,
    banned_tokens: [],
    sampler_order: [6, 3, 2, 5, 0, 1, 4],
    top_k: 100,
    top_p: 1,
    top_a: 0,
    min_p: 0.6,
    presence_penalty: 0.6,
    frequency_penalty: 0.8,
    tfs: 1,
    typical: 1,
    singleline: false,
    sampler_full_determinism: true,
    min_tokens: 0,
    context_length: 8096,
    max_tokens: 250,
    mirostat_mode: 0,
    mirostat_tau: 0,
    mirostat_eta: 0,
    instruct_mode: 'None',
    use_beam_search: false,
    eta_cutoff: 0,
    epsilon_cutoff: 0,
    dynatemp_exponent: 0,
    dynatemp_max: 0,
    dynatemp_min: 0,
    length_penalty: false,
  },
  {
    id: '32',
    name: 'Pleasing Results',
    rep_pen: 1.1,
    rep_pen_range: 4096,
    rep_pen_slope: 0.9,
    temperature: 0.83,
    banned_tokens: [],
    sampler_order: [6, 3, 2, 5, 0, 1, 4],
    top_k: 25,
    top_p: 1,
    top_a: 0,
    min_p: 0.6,
    presence_penalty: 0.6,
    frequency_penalty: 0.8,
    tfs: 1,
    typical: 1,
    singleline: false,
    sampler_full_determinism: true,
    min_tokens: 0,
    context_length: 8096,
    max_tokens: 250,
    mirostat_mode: 0,
    mirostat_tau: 0,
    mirostat_eta: 0,
    instruct_mode: 'None',
    use_beam_search: false,
    eta_cutoff: 0,
    epsilon_cutoff: 0,
    dynatemp_exponent: 0,
    dynatemp_max: 0,
    dynatemp_min: 0,
    length_penalty: false,
  },
  {
    "id": "48",
    "name": "Recovered Ruins",
    "rep_pen": 1.4,
    "rep_pen_range": 1024,
    "rep_pen_slope": 0.5,
    "temperature": 0.7,
    "banned_tokens": [],
    "sampler_order": [5, 4, 3, 2, 1, 0, 6],
    "top_k": 40,
    "top_p": 0.9,
    "top_a": 0.1,
    "min_p": 0.4,
    "presence_penalty": 0.3,
    "frequency_penalty": 0.5,
    "tfs": 0.8,
    "typical": 0.7,
    "singleline": true,
    "sampler_full_determinism": false,
    "min_tokens": 10,
    "context_length": 4096,
    "max_tokens": 150,
    "mirostat_mode": 1,
    "mirostat_tau": 2,
    "mirostat_eta": 0.2,
    instruct_mode: 'None',
    use_beam_search: false,
    eta_cutoff: 0,
    epsilon_cutoff: 0,
    dynatemp_exponent: 0,
    dynatemp_max: 0,
    dynatemp_min: 0,
    length_penalty: false,
  },
  {
    "id": "54",
    "name": "Space Alien",
    "rep_pen": 1.5,
    "rep_pen_range": 2048,
    "rep_pen_slope": 0.6,
    "temperature": 0.9,
    "banned_tokens": [],
    "sampler_order": [1, 2, 3, 4, 5, 6, 0],
    "top_k": 30,
    "top_p": 0.85,
    "top_a": 0.15,
    "min_p": 0.5,
    "presence_penalty": 0.4,
    "frequency_penalty": 0.6,
    "tfs": 0.9,
    "typical": 0.8,
    "singleline": true,
    "sampler_full_determinism": false,
    "min_tokens": 15,
    "context_length": 5120,
    "max_tokens": 200,
    "mirostat_mode": 2,
    "mirostat_tau": 3,
    "mirostat_eta": 0.3,
    instruct_mode: 'None',
    use_beam_search: false,
    eta_cutoff: 0,
    epsilon_cutoff: 0,
    dynatemp_exponent: 0,
    dynatemp_max: 0,
    dynatemp_min: 0,
    length_penalty: false,
  },
  {
    "id": "60",
    "name": "Storywriter",
    "rep_pen": 1.3,
    "rep_pen_range": 1500,
    "rep_pen_slope": 0.4,
    "temperature": 0.8,
    "banned_tokens": [],
    "sampler_order": [2, 1, 0, 3, 4, 5, 6],
    "top_k": 50,
    "top_p": 0.75,
    "top_a": 0.25,
    "min_p": 0.55,
    "presence_penalty": 0.5,
    "frequency_penalty": 0.7,
    "tfs": 0.85,
    "typical": 0.9,
    "singleline": false,
    "sampler_full_determinism": true,
    "min_tokens": 20,
    "context_length": 6000,
    "max_tokens": 180,
    "mirostat_mode": 3,
    "mirostat_tau": 4,
    "mirostat_eta": 0.25,
    instruct_mode: 'None',
    use_beam_search: false,
    eta_cutoff: 0,
    epsilon_cutoff: 0,
    dynatemp_exponent: 0,
    dynatemp_max: 0,
    dynatemp_min: 0,
    length_penalty: false,
  },
  {
    "id": "75",
    "name": "TFS with Top A",
    "rep_pen": 1.2,
    "rep_pen_range": 2500,
    "rep_pen_slope": 0.7,
    "temperature": 0.6,
    "banned_tokens": [],
    "sampler_order": [3, 2, 1, 0, 4, 5, 6],
    "top_k": 35,
    "top_p": 0.8,
    "top_a": 0.2,
    "min_p": 0.45,
    "presence_penalty": 0.35,
    "frequency_penalty": 0.65,
    "tfs": 0.95,
    "typical": 0.75,
    "singleline": true,
    "sampler_full_determinism": false,
    "min_tokens": 25,
    "context_length": 7000,
    "max_tokens": 175,
    "mirostat_mode": 4,
    "mirostat_tau": 6,
    "mirostat_eta": 0.35,
    instruct_mode: 'None',
    use_beam_search: false,
    eta_cutoff: 0,
    epsilon_cutoff: 0,
    dynatemp_exponent: 0,
    dynatemp_max: 0,
    dynatemp_min: 0,
    length_penalty: false,
  },
  {
    "id": "89",
    "name": "Titanic",
    "rep_pen": 1.6,
    "rep_pen_range": 3000,
    "rep_pen_slope": 0.8,
    "temperature": 0.5,
    "banned_tokens": [],
    "sampler_order": [4, 3, 2, 1, 0, 5, 6],
    "top_k": 45,
    "top_p": 0.7,
    "top_a": 0.3,
    "min_p": 0.35,
    "presence_penalty": 0.2,
    "frequency_penalty": 0.4,
    "tfs": 0.7,
    "typical": 0.6,
    "singleline": false,
    "sampler_full_determinism": true,
    "min_tokens": 30,
    "context_length": 8000,
    "max_tokens": 220,
    "mirostat_mode": 5,
    "mirostat_tau": 7,
    "mirostat_eta": 0.4,
    instruct_mode: 'None',
    use_beam_search: false,
    eta_cutoff: 0,
    epsilon_cutoff: 0,
    dynatemp_exponent: 0,
    dynatemp_max: 0,
    dynatemp_min: 0,
    length_penalty: false,
  },
]